---
- hosts: workers
  gather_facts: yes

  tasks:
    - name: Copy join command from host to worker nodes
      copy:
        src: /tmp/token.sh/control1/token.sh
        dest: /tmp/kubernetes_join_command
        mode: 0700

    - name: Join the worker nodes to the cluster
      become: yes
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not